In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats
#from scipy.stats import norm
import sklearn
import statsmodels.api as sm

import datetime
%matplotlib inline

#sns.set(style="dark")
plt.style.use("ggplot")

In [ ]:
pip install pyperclip

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11135 sha256=cc98cf5a3eae41bcb8fbfaa9b9775a1c70ee7ec7fba42a16cb734baee68cdce2
  Stored in directory: /root/.cache/pip/wheels/0c/09/9e/49e21a6840ef7955b06d47394afef0058f0378c0914e48b8b8
Successfully built pyperclip


In [ ]:
import pyperclip

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving driverpay.csv to driverpay.csv
Saving rideduration.csv to rideduration.csv
Saving speed.csv to speed.csv
Saving waitingtime.csv to waitingtime.csv


In [ ]:
#Loads CSVs of data

#Driver pay is in $
#Ride duration is in seconds
#Speed is in mph
#Waiting time is in seconds

driverpay = pd.read_csv('driverpay.csv')
rideduration = pd.read_csv('rideduration.csv')
speed = pd.read_csv('speed.csv')
waitingtime = pd.read_csv('waitingtime.csv')

In [ ]:
#Gets the mean and SDs of every variable of interest

driverpay_avg = driverpay.groupby('Company').mean().round(0).reset_index()
rideduration_avg = rideduration.groupby('Company').mean().round(0).reset_index()
speed_avg = speed.groupby('Company').mean().round(0).reset_index()
waitingtime_avg = waitingtime.groupby('Company').mean().round(0).reset_index()


Company   Mean     SD
0    Uber  296.0  188.0
1     Via  635.0  295.0

# Uber Distributions

In [ ]:
#sets size for amount we want to pull for each
n = 400

### Driver Pay Arrays

In [ ]:
#Generates 2 arrays: 1 array for "short" driver pays and one for "long" driver pays
#short is anything below the mean, and long is anything above the mean

np.random.seed(50)

driverpay_mean = 16.54
driverpay_SD = 16.72

driverpay_short, driverpay_long = [], []

distribution = np.random.normal(driverpay_mean, driverpay_SD, n).round(2)
for i in distribution:
  if i >= 0:
    if i < driverpay_mean:
      driverpay_short.append(i)
    else:
      driverpay_long.append(i)

driverpay_long

[40.15,
 34.43,
 18.65,
 30.96,
 28.19,
 43.27,
 71.95,
 33.06,
 18.61,
 28.96,
 19.02,
 18.87,
 21.31,
 45.15,
 28.08,
 34.85,
 38.92,
 24.67,
 29.14,
 22.62,
 39.5,
 22.82,
 28.96,
 30.88,
 22.87,
 27.98,
 61.77,
 18.14,
 25.31,
 30.18,
 17.4,
 21.19,
 18.0,
 17.11,
 29.02,
 35.07,
 17.19,
 20.26,
 20.75,
 28.38,
 24.8,
 41.14,
 51.08,
 34.73,
 30.0,
 37.12,
 22.4,
 18.84,
 28.72,
 43.66,
 41.98,
 16.63,
 31.03,
 17.33,
 21.5,
 30.62,
 19.89,
 30.73,
 46.77,
 31.09,
 29.06,
 28.4,
 21.83,
 23.63,
 35.98,
 57.74,
 39.66,
 29.65,
 19.25,
 37.65,
 43.88,
 22.09,
 27.58,
 41.95,
 16.57,
 22.08,
 31.34,
 16.71,
 19.14,
 59.67,
 16.86,
 28.99,
 17.34,
 28.67,
 61.89,
 17.91,
 17.62,
 46.16,
 39.45,
 25.99,
 17.5,
 20.58,
 24.67,
 24.72,
 27.16,
 29.94,
 23.88,
 19.14,
 41.57,
 30.55,
 20.48,
 42.92,
 45.64,
 34.76,
 36.97,
 24.42,
 25.98,
 25.99,
 28.49,
 37.95,
 22.81,
 33.29,
 23.7,
 40.94,
 22.43,
 23.38,
 29.27,
 22.96,
 35.34,
 23.36,
 27.94,
 47.44,
 31.47,
 53.36,
 31.54,
 26.2,
 27

### Ride Duration Arrays

In [ ]:
#Generates 2 arrays: 1 array for "short" ride durations and one for "long" ride durations
#short is anything below the mean, and long is anything above the mean

np.random.seed(50)

rideduration_short, rideduration_long = [], []

distribution = np.random.normal(rideduration_avg.Mean.iloc[0], rideduration_avg.SD.iloc[0], n)

for i in distribution:
    if i >= 60:
      if i < rideduration_avg.Mean.iloc[0]:
        rideduration_short.append(i)
      else:
        rideduration_long.append(i)

rideduration_short = (np.asarray(rideduration_short)/60).round(0)
rideduration_long = (np.asarray(rideduration_long)/60).round(0)

rideduration_long

array([52., 47., 35., 45., 42., 55., 78., 46., 35., 43., 35., 35., 37.,
       56., 42., 48., 51., 40., 43., 38., 52., 38., 43., 45., 38., 42.,
       69., 34., 40., 44., 34., 37., 34., 34., 43., 48., 34., 36., 36.,
       43., 40., 53., 61., 48., 44., 50., 38., 35., 43., 55., 54., 33.,
       45., 34., 37., 44., 36., 44., 57., 45., 43., 43., 37., 39., 49.,
       66., 52., 44., 35., 50., 55., 38., 42., 54., 33., 38., 45., 33.,
       35., 68., 33., 43., 34., 43., 70., 34., 34., 57., 51., 41., 34.,
       36., 40., 40., 42., 44., 39., 35., 53., 44., 36., 54., 56., 48.,
       50., 39., 41., 41., 43., 50., 38., 47., 39., 53., 38., 39., 43.,
       38., 48., 39., 42., 58., 45., 63., 45., 41., 42., 42., 38., 64.,
       45., 42., 44., 42., 45., 44., 34., 39., 37., 40., 44., 49., 37.,
       48., 34., 41., 44., 50., 44., 35., 58., 47., 35., 41., 37., 58.,
       36., 41., 37., 52., 36., 41., 55., 38., 43., 36., 36., 50., 47.,
       42., 35., 58., 40., 37., 34., 52., 34., 46., 49., 33., 55

### Speed Arrays

In [ ]:
#Generates 2 arrays: 1 array for "short" speeds and one for "long" speeds
#short is anything below the mean, and long is anything above the mean

np.random.seed(50)

speed_short, speed_long = [], []

distribution = np.random.normal(speed_avg.Mean.iloc[0], speed_avg.SD.iloc[0], n)

for i in distribution:
    if i >= 0:
      if i < speed_avg.Mean.iloc[0]:
        speed_short.append(i)
      else:
        speed_long.append(i)

speed_short = np.asarray(speed_short).round(0)
speed_long = np.asarray(speed_long).round(0)

speed_short

array([12., 21., 17., 12., 18., 16., 13., 13., 19., 15., 19., 19., 20.,
       19., 20., 13., 19., 17., 20., 12., 11., 20., 19., 14., 16., 21.,
       12., 20., 15., 20., 20., 16., 19., 18., 11.,  7., 21., 20., 21.,
       17., 19.,  6., 17., 13., 16., 18., 19., 18., 20., 20., 20., 20.,
       16.,  6., 18., 20., 13., 11., 11., 14., 14., 14., 16., 18., 14.,
       15., 14., 21., 17., 20., 12., 20., 14., 18., 15., 18., 17., 19.,
       19., 17., 16., 21., 16., 18., 18., 10., 17., 16., 20., 21., 21.,
       13., 12., 12., 15., 11., 18.,  4., 13., 13., 20., 20., 18., 21.,
       15., 21., 20., 15., 18., 15., 19., 19., 19., 12., 13., 18., 19.,
       21., 16., 20., 12., 14., 14., 17., 11., 18.,  9., 14., 20., 15.,
       17., 12., 20., 12., 20., 16., 20., 19., 18., 19., 18., 16., 10.,
       19., 18., 20., 16., 18., 14., 18., 17., 16., 18.,  9., 19.,  9.,
       13., 14., 17., 20., 16.,  9., 17., 14., 14., 11., 10., 19., 16.,
       20., 14., 16., 18., 15., 19., 20., 17., 17., 10., 19., 20

### Waiting Time Arrays

In [ ]:
#Generates 2 arrays: 1 array for "short" waiting times and one for "long" waiting times
#short is anything below the mean, and long is anything above the mean

np.random.seed(50)

waitingtime_short, waitingtime_long = [], []

distribution = np.random.normal(waitingtime_avg.Mean.iloc[0], waitingtime_avg.SD.iloc[0], n)

for i in distribution:
    if i >= 60 and i <= 600:
      if i < waitingtime_avg.Mean.iloc[0]:
        waitingtime_short.append(i)
      else:
        waitingtime_long.append(i)

waitingtime_short = (np.asarray(waitingtime_short)/60).round(0)
waitingtime_long = (np.asarray(waitingtime_long)/60).round(0)

waitingtime_long

array([ 9.,  8.,  5.,  8.,  7., 10.,  8.,  5.,  7.,  5.,  5.,  6.,  7.,
        8.,  9.,  6.,  7.,  6.,  9.,  6.,  7.,  8.,  6.,  7.,  5.,  7.,
        7.,  5.,  6.,  5.,  5.,  7.,  8.,  5.,  6.,  6.,  7.,  6., 10.,
        8.,  7.,  9.,  6.,  5.,  7., 10.,  5.,  8.,  5.,  6.,  8.,  6.,
        8.,  8.,  7.,  7.,  6.,  6.,  9.,  9.,  7.,  5.,  9.,  6.,  7.,
       10.,  5.,  6.,  8.,  5.,  5.,  5.,  7.,  5.,  7.,  5.,  5.,  9.,
        7.,  5.,  6.,  6.,  6.,  7.,  7.,  6.,  5., 10.,  8.,  6., 10.,
        8.,  9.,  6.,  7.,  7.,  7.,  9.,  6.,  8.,  6., 10.,  6.,  6.,
        7.,  6.,  8.,  6.,  7.,  8.,  8.,  7.,  7.,  7.,  6.,  8.,  7.,
        8.,  7.,  8.,  7.,  5.,  6.,  6.,  6.,  8.,  9.,  6.,  8.,  5.,
        7.,  8.,  9.,  7.,  5.,  8.,  5.,  7.,  6.,  6.,  7.,  6.,  9.,
        6.,  7., 10.,  6.,  7.,  6.,  6.,  9.,  8.,  7.,  5.,  6.,  6.,
        5.,  9.,  5.,  8.,  9.,  5.,  5.,  8.,  5.,  8.,  7.,  7.,  6.])

# Via Distributions

In [ ]:
#sets size for amount we want to pull for each
n = 500

### Driver Pay Arrays

In [ ]:
np.random.seed(50)

driverpay_short, driverpay_long = [], []

distribution = np.random.normal(driverpay_avg.Mean.iloc[1], driverpay_avg.SD.iloc[1], n).round(2)

for i in distribution:
  if i >= 0:
    if i < driverpay_avg.Mean.iloc[0]:
      driverpay_short.append(i)
    else:
      driverpay_long.append(i)

### Ride Duration Arrays

In [ ]:
np.random.seed(50)

rideduration_short, rideduration_long = [], []

distribution = np.random.normal(rideduration_avg.Mean.iloc[1], rideduration_avg.SD.iloc[1], n)

for i in distribution:
    if i >= 60:
      if i < rideduration_avg.Mean.iloc[0]:
        rideduration_short.append(i)
      else:
        rideduration_long.append(i)

rideduration_short = (np.asarray(rideduration_short)/60).round(0)
rideduration_long = (np.asarray(rideduration_long)/60).round(0)

rideduration_short

array([13., 25., 14., 27., 23., 17., 16., 29., 20., 28., 28., 32., 30.,
       32., 15., 30., 25., 31., 14., 12., 31., 29., 18., 23., 14., 32.,
       21., 30., 31., 22., 30., 26., 13.,  2., 31., 33., 25., 29., 24.,
       16., 22., 27., 30., 28., 32., 31., 31., 31., 24.,  1., 27., 32.,
       17., 11., 13., 19., 18., 19., 23., 27., 18., 21., 19., 25., 32.,
       13., 32., 18., 27., 21., 26., 24., 29., 29., 24., 22., 33., 22.,
       26., 26.,  9., 25., 23., 31., 33., 17., 14., 15., 20., 12., 28.,
       17., 15., 31., 32., 27., 33., 21., 33., 33., 21., 26., 19., 29.,
       28., 29., 15., 17., 27., 30., 33., 22., 30., 14., 19., 19., 24.,
       11., 28.,  7., 17., 32., 21., 26., 15., 30., 14., 31., 22., 30.,
       28., 26., 30., 27., 22., 10., 28., 28., 31., 23., 28., 19., 26.,
       26., 23., 27.,  8., 28.,  8., 16., 19., 25., 32., 23.,  7., 24.,
       18., 18., 12., 10., 30., 22., 32., 18., 23., 27., 20., 29., 32.,
       24., 24., 10., 29., 31., 24., 18., 25., 32., 32., 22., 28

### Speed Arrays

In [ ]:
np.random.seed(50)

speed_short, speed_long = [], []

distribution = np.random.normal(speed_avg.Mean.iloc[1], speed_avg.SD.iloc[1], n)

for i in distribution:
    if i >= 0:
      if i < speed_avg.Mean.iloc[0]:
        speed_short.append(i)
      else:
        speed_long.append(i)

speed_short = np.asarray(speed_short).round(0)
speed_long = np.asarray(speed_long).round(0)

speed_short

array([11., 18., 12., 19., 17., 13., 13., 20., 15., 19., 19., 21., 20.,
       21., 12., 20., 18., 21., 11., 10., 20., 19., 14., 16., 12., 21.,
       15., 20., 21., 16., 20., 18., 11.,  5., 21., 18., 19.,  4., 17.,
       13., 16., 18., 20., 19., 21., 21., 21., 17.,  5., 18., 21., 13.,
       10., 11., 14., 14., 14., 17., 18., 14., 15., 14., 18., 11., 21.,
       13., 18., 16., 18., 17., 20., 19., 17., 16., 16., 18., 18.,  9.,
       17., 16., 20., 13., 12., 12., 15., 11., 19.,  2., 13., 12., 21.,
       21., 18., 15., 15., 18., 15., 19., 19., 20., 12., 13., 19., 20.,
       16., 20., 12., 14., 14., 17., 10., 19.,  8., 13., 21., 15., 18.,
       12., 20., 11., 21., 16., 20., 19., 18., 20., 19., 16.,  9., 19.,
       19., 20., 17., 19., 14., 18., 18., 16., 19.,  8., 19.,  8., 13.,
       14., 18., 16.,  8., 17., 14., 14., 11.,  9., 20., 16., 21., 14.,
       16., 19., 15., 19., 17., 17., 10., 20., 20., 17., 14., 17., 21.,
       16., 19., 20., 19., 19., 18., 13., 18., 17., 17., 17., 18

### Waiting Time Arrays

In [ ]:
np.random.seed(50)

waitingtime_short, waitingtime_long = [], []

distribution = np.random.normal(waitingtime_avg.Mean.iloc[1], waitingtime_avg.SD.iloc[1], n)

for i in distribution:
    if i >= 60:
      if i < waitingtime_avg.Mean.iloc[0]:
        waitingtime_short.append(i)
      else:
        waitingtime_long.append(i)

waitingtime_short = (np.asarray(waitingtime_short)/60).round(0)
waitingtime_long = (np.asarray(waitingtime_long)/60).round(0)

waitingtime_long

array([10.,  8., 18.,  8.,  7., 16., 11., 15., 14.,  9.,  6., 18., 27.,
       15., 11., 14.,  9., 11.,  9., 10., 11., 12.,  9., 19., 10., 14.,
       16., 17., 13., 14., 12.,  9., 17.,  8., 12., 10., 14., 15., 10.,
        9., 12., 14.,  7., 10., 24., 11., 13., 15., 11., 10., 12., 11.,
       11., 14.,  6.,  9., 16., 11., 10.,  6.,  9., 12., 12., 14., 13.,
       18.,  8., 21., 16., 15., 17., 10., 10., 12., 10.,  7.,  9., 11.,
        7., 14., 19., 18.,  6., 11., 15.,  8.,  9., 11.,  8., 10., 10.,
       10., 10., 12.,  7.,  8., 15., 10., 12., 15.,  5., 19.,  5., 15.,
       14., 14., 12.,  7.,  8.,  6.,  5., 10.,  7., 13., 16., 23., 10.,
       17., 10., 14.,  8., 11.,  6., 17., 19., 12.,  8.,  7.,  9.,  9.,
        7., 14.,  6., 10., 18.,  6., 11.,  8., 12.,  8.,  7.,  6., 15.,
        9., 11., 11., 10.,  6., 11., 23.,  8., 11., 14., 11., 14., 10.,
       10.,  8., 24., 10., 11., 11.,  6., 10., 10., 19.,  6., 17.,  8.,
        5., 13., 11., 12., 13.,  9., 13., 14., 15.,  9.,  9., 13

# Combinations

Combinations (disregarding speed for now)
- Long Wait Time, Long Ride Duration, High Driver Pay
- Long Wait Time, Long Ride Duration, Low Driver Pay
- Long Wait Time, Short Ride Duration, High Driver Pay
- Long Wait Time, Short Ride Duration, Low Driver Pay

- Short Wait Time, Long Ride Duration, High Driver Pay
- Short Wait Time, Long Ride Duration, Low Driver Pay
- Short Wait Time, Short Ride Duration, High Driver Pay
- Short Wait Time, Short Ride Duration, Low Driver Pay



More Basic Combos (in this case, high driver pay would be associated with long ride duration)
- Long Wait Time, Long Ride Duration
- Long Wait Time, Short Ride Duration
- Short Wait Time, Short Ride Duration
- Short Wait Time, Long Ride Duration

## Uber Combinations

In [ ]:
waitingtimes = [waitingtime_short, waitingtime_long]
driverpays = [driverpay_short, driverpay_long]
ridedurations = [driverpay_short, driverpay_long]

In [ ]:
data = {'A_driver_pay_long': driverpay_long}

df = pd.DataFrame(data)

df.to_csv('check.csv')

In [ ]:
#Randomly generates 250 values of 0 and 1 to determine if waiting time will be long or short
np.random.seed(50)

waitingtime_length = np.random.choice([0, 1], size=(250,), p=[1./2, 1/2])
waitingtime_length

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
waitingtime_lengths = repr(waitingtime_length).replace(" ", "")
print(waitingtime_lengths)

array([0,0,0,0,0,1,0,1,1,0,0,0,0,1,1,1,0,1,1,0,1,1,
1,1,1,0,0,0,0,1,1,1,1,0,1,0,1,1,1,0,1,1,1,0,
1,1,1,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,1,1,
1,1,1,0,1,1,0,1,1,1,1,0,0,0,0,1,0,0,1,1,1,1,
0,1,1,1,0,1,0,1,0,0,1,0,0,0,0,0,0,1,1,0,0,1,
1,1,0,1,1,0,0,1,0,1,1,0,0,0,0,0,0,1,1,0,0,0,
1,0,0,0,1,1,0,0,0,0,0,1,1,0,1,1,0,1,1,1,0,0,
1,1,0,1,1,1,0,0,0,0,0,0,1,0,1,1,0,0,0,1,0,1,
0,1,1,0,1,0,1,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,
0,1,1,1,0,1,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,
0,1,1,1,1,0,0,1,1,0,0,0,1,0,0,1,0,1,0,0,0,1,
1,1,0,0,1,0,1,0])


In [ ]:
np.random.seed(28)

ridedurations_length = np.random.choice([0, 1], size=(250,), p=[1./2, 1/2])
ridedurations_length

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1])

In [ ]:
ridedurations_lengths = repr(ridedurations_length).replace(" ", "")
print(ridedurations_lengths)

array([1,1,0,0,1,1,0,1,1,1,0,1,0,0,1,1,0,0,0,1,0,0,
1,1,1,1,0,0,1,0,1,1,0,0,1,0,1,1,1,0,0,1,0,1,
1,0,1,1,1,0,1,0,1,0,1,0,1,0,0,1,1,1,1,0,1,0,
1,0,1,0,1,0,1,1,0,0,0,1,0,1,0,1,0,1,1,0,1,1,
1,1,1,1,0,1,0,0,0,1,0,1,0,1,0,0,0,1,0,0,1,1,
1,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,1,1,0,1,0,1,
1,1,0,1,1,0,0,1,0,0,0,0,0,0,1,1,1,0,1,1,0,1,
1,1,0,0,0,1,0,0,1,1,0,0,1,0,0,0,0,1,1,1,0,1,
0,1,1,1,0,1,0,1,0,0,1,0,1,0,1,1,0,0,1,1,1,0,
0,0,1,1,0,1,1,0,0,0,1,0,0,1,0,0,1,1,0,0,1,1,
1,0,1,0,1,1,1,0,1,0,0,0,1,1,0,1,0,0,0,0,1,1,
1,1,0,0,0,0,0,1])


In [ ]:
waitingtime_short = repr(waitingtime_short).replace(".", "").replace(" ", "")
print(waitingtime_short)

array([5,3,3,2,4,2,4,4,4,4,4,4,3,4,4,4,1,
2,5,4,2,4,4,2,4,3,5,4,5,3,4,3,2,3,
4,4,5,4,4,4,3,3,4,1,1,1,2,3,1,2,1,
5,3,5,4,1,3,2,3,3,4,4,3,2,5,2,3,3,
3,2,4,5,5,2,4,4,4,3,5,2,5,5,2,3,2,
4,4,4,3,4,5,2,4,1,1,3,3,1,4,2,3,4,
4,2,4,4,3,4,3,2,4,4,4,3,4,1,3,3,2,
3,4,2,3,5,2,3,1,1,4,2,4,1,2,3,2,4,
5,3,3,4,4,3,1,3,5,4,2,4,4,4,3,3,3,
3,2,3,3,4,5,4,3,3,2,5,3,3,2,2])


In [ ]:
waitingtime_long = repr(waitingtime_long).replace(".", "").replace(" ", "")
print(waitingtime_long)

array([9,8,5,8,7,10,8,5,7,5,5,6,7,
8,9,6,7,6,9,6,7,8,6,7,5,7,
7,5,6,5,5,7,8,5,6,6,7,6,10,
8,7,9,6,5,7,10,5,8,5,6,8,6,
8,8,7,7,6,6,9,9,7,5,9,6,7,
10,5,6,8,5,5,5,7,5,7,5,5,9,
7,5,6,6,6,7,7,6,5,10,8,6,10,
8,9,6,7,7,7,9,6,8,6,10,6,6,
7,6,8,6,7,8,8,7,7,7,6,8,7,
8,7,8,7,5,6,6,6,8,9,6,8,5,
7,8,9,7,5,8,5,7,6,6,7,6,9,
6,7,10,6,7,6,6,9,8,7,5,6,6,
5,9,5,8,9,5,5,8,5,8,7,7,6])


In [ ]:
rideduration_short
rideduration_short = repr(rideduration_short).replace(".", "").replace(" ", "")
print(rideduration_short)

array([12,33,25,13,27,23,16,15,29,20,28,28,31,
29,31,15,29,25,30,13,11,30,28,17,22,33,
13,31,20,30,30,21,29,25,12,1,33,30,32,
25,28,23,15,21,26,30,27,31,31,30,30,23,
26,31,16,10,12,18,18,18,23,26,17,20,18,
33,24,31,12,31,17,26,21,26,23,29,28,23,
22,32,21,26,26,8,24,22,30,33,32,16,13,
14,20,12,27,16,14,30,31,26,32,21,32,32,
20,25,19,28,28,28,14,16,27,29,32,21,30,
13,18,18,23,10,27,6,16,31,20,25,14,30,
13,30,21,30,28,26,29,26,22,9,28,27,30,
23,27,18,26,25,22,27,7,28,7,15,18,25,
31,22,6,23,17,17,12,9,29,21,31,17,22,
27,19,28,32,23,24,9,28,30,23,17,24,32,
31,21,27,30,28,27,26,15,25,24,23,24,26,
12,30,32,15,30,25,27,21,33,24,24,18,21])


In [ ]:
rideduration_long = repr(rideduration_long).replace(".", "").replace(" ", "")
print(rideduration_long)

array([52,47,35,45,42,55,78,46,35,43,35,35,37,
56,42,48,51,40,43,38,52,38,43,45,38,42,
69,34,40,44,34,37,34,34,43,48,34,36,36,
43,40,53,61,48,44,50,38,35,43,55,54,33,
45,34,37,44,36,44,57,45,43,43,37,39,49,
66,52,44,35,50,55,38,42,54,33,38,45,33,
35,68,33,43,34,43,70,34,34,57,51,41,34,
36,40,40,42,44,39,35,53,44,36,54,56,48,
50,39,41,41,43,50,38,47,39,53,38,39,43,
38,48,39,42,58,45,63,45,41,42,42,38,64,
45,42,44,42,45,44,34,39,37,40,44,49,37,
48,34,41,44,50,44,35,58,47,35,41,37,58,
36,41,37,52,36,41,55,38,43,36,36,50,47,
42,35,58,40,37,34,52,34,46,49,33,55,34,
46,35,44,41,42,37])


In [ ]:
driverpay_short = repr(driverpay_short).replace(" ", "")
print(driverpay_short)

"'[12.59,35.54,26.69,14.03,28.85,24.29,16.77,16.09,30.98,21.04,30.09,29.82,33.59,31.78,33.75,15.47,31.28,26.63,32.99,13.41,11.0,32.72,30.62,18.48,24.1,35.42,13.63,33.53,21.85,32.31,32.8,22.64,31.94,27.26,12.18,0.4,35.53,33.01,35.21,26.49,30.56,25.21,16.4,22.65,27.97,32.13,29.59,34.18,33.47,33.06,33.1,24.6,28.04,33.53,16.74,10.35,12.24,19.49,18.64,19.33,24.33,27.96,18.39,21.98,19.5,35.58,26.39,33.95,12.36,33.61,17.76,28.11,22.15,27.65,25.23,31.11,30.25,25.31,23.33,34.85,22.85,27.67,27.79,7.84,25.72,23.49,32.61,35.9,34.91,17.04,13.69,14.64,20.91,12.05,29.56,16.63,15.18,32.89,33.84,28.11,34.83,22.04,35.03,34.72,21.52,27.49,19.96,30.55,30.02,30.83,14.52,16.94,28.74,31.45,35.12,22.86,32.35,14.15,19.4,18.93,24.91,10.75,29.07,5.68,17.39,33.62,21.25,26.88,14.54,32.28,13.35,33.05,22.8,32.38,29.98,27.67,31.86,28.52,23.37,8.92,29.92,29.27,32.64,24.37,29.55,19.41,27.71,27.22,23.89,28.72,6.72,30.12,6.81,15.72,19.75,26.69,34.12,23.54,5.89,25.12,18.45,18.6,11.98,9.18,31.56,22.31,33.85,17.82,23.78,29.

In [ ]:
driverpay_long = repr(driverpay_long).replace(" ", "")
print(driverpay_long)

[57.18,52.05,37.9,48.93,46.45,59.98,85.71,50.82,37.86,47.14,38.22,38.09,40.28,61.66,46.35,52.43,56.08,43.3,47.3,41.45,56.6,41.64,47.15,48.86,41.68,46.26,76.58,37.44,43.87,48.23,36.77,40.17,37.31,36.51,47.2,52.62,36.59,39.33,39.78,46.62,43.41,58.07,66.99,52.32,48.08,54.46,41.26,38.06,46.93,60.33,58.82,36.08,49.0,36.71,40.45,48.64,39.0,48.73,63.12,49.06,47.23,46.64,40.74,42.36,53.44,72.97,56.74,47.76,38.43,54.94,60.53,40.98,45.91,58.8,36.02,40.97,49.28,36.15,38.33,74.69,36.29,47.17,36.72,46.88,76.68,37.23,36.96,62.58,56.56,44.48,36.86,39.62,43.29,43.34,45.53,48.02,42.58,38.33,58.45,48.57,39.54,59.67,62.11,52.34,54.33,43.07,44.46,44.48,46.72,55.2,41.63,51.03,42.43,57.89,41.28,42.13,47.42,41.76,52.86,42.11,46.23,63.73,49.4,69.03,49.46,44.67,45.52,46.34,42.02,70.9,49.0,45.61,48.69,46.14,49.8,48.12,36.85,42.62,40.43,43.23,48.68,53.22,40.49,52.47,36.8,44.61,48.3,55.19,48.22,38.24,64.27,51.47,37.73,44.86,39.86,63.35,39.55,44.88,39.88,57.54,39.63,44.63,60.05,41.88,46.92,39.35,39.23,54.86,52.07,

In [ ]:
arrays = [waitingtime_short, waitingtime_long,
          rideduration_short, rideduration_long,
          driverpay_short, driverpay_long]

for i in arrays:
  print(repr(i).replace(".", ","))

array([5,3,3,2,4,2,4,4,4,4,4,4,3,4,4,4,1.,
       2,5,4,2,4,4,2,4,3,5,4,5,3,4,3,2,3.,
       4,4,5,4,4,4,3,3,4,1,1,1,2,3,1,2,1.,
       5,3,5,4,1,3,2,3,3,4,4,3,2,5,2,3,3.,
       3,2,4,5,5,2,4,4,4,3,5,2,5,5,2,3,2.,
       4,4,4,3,4,5,2,4,1,1,3,3,1,4,2,3,4.,
       4,2,4,4,3,4,3,2,4,4,4,3,4,1,3,3,2.,
       3,4,2,3,5,2,3,1,1,4,2,4,1,2,3,2,4.,
       5,3,3,4,4,3,1,3,5,4,2,4,4,4,3,3,3.,
       3,2,3,3,4,5,4,3,3,2,5,3,3,2,2.])
array([ 9, 8, 5, 8, 7,10, 8, 5, 7, 5, 5, 6, 7.,
        8, 9, 6, 7, 6, 9, 6, 7, 8, 6, 7, 5, 7.,
        7, 5, 6, 5, 5, 7, 8, 5, 6, 6, 7, 6,10.,
        8, 7, 9, 6, 5, 7,10, 5, 8, 5, 6, 8, 6.,
        8, 8, 7, 7, 6, 6, 9, 9, 7, 5, 9, 6, 7.,
       10, 5, 6, 8, 5, 5, 5, 7, 5, 7, 5, 5, 9.,
        7, 5, 6, 6, 6, 7, 7, 6, 5,10, 8, 6,10.,
        8, 9, 6, 7, 7, 7, 9, 6, 8, 6,10, 6, 6.,
        7, 6, 8, 6, 7, 8, 8, 7, 7, 7, 6, 8, 7.,
        8, 7, 8, 7, 5, 6, 6, 6, 8, 9, 6, 8, 5.,
        7, 8, 9, 7, 5, 8, 5, 7, 6, 6, 7, 6, 9.,
        6, 7,10, 6, 7, 6, 6, 9, 8, 7, 5, 6, 6

## Via Combinations

In [ ]:
waitingtimes = [waitingtime_short, waitingtime_long]
driverpays = [driverpay_short, driverpay_long]
ridedurations = [driverpay_short, driverpay_long]

In [ ]:
np.random.seed(50)

waitingtime_length = np.random.choice([0, 1], size=(250,), p=[1./2, 1/2])
waitingtime_length

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
waitingtime_lengths = repr(waitingtime_length).replace(" ", "")
print(waitingtime_lengths)

array([0,0,0,0,0,1,0,1,1,0,0,0,0,1,1,1,0,1,1,0,1,1,
1,1,1,0,0,0,0,1,1,1,1,0,1,0,1,1,1,0,1,1,1,0,
1,1,1,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,1,1,
1,1,1,0,1,1,0,1,1,1,1,0,0,0,0,1,0,0,1,1,1,1,
0,1,1,1,0,1,0,1,0,0,1,0,0,0,0,0,0,1,1,0,0,1,
1,1,0,1,1,0,0,1,0,1,1,0,0,0,0,0,0,1,1,0,0,0,
1,0,0,0,1,1,0,0,0,0,0,1,1,0,1,1,0,1,1,1,0,0,
1,1,0,1,1,1,0,0,0,0,0,0,1,0,1,1,0,0,0,1,0,1,
0,1,1,0,1,0,1,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,
0,1,1,1,0,1,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,
0,1,1,1,1,0,0,1,1,0,0,0,1,0,0,1,0,1,0,0,0,1,
1,1,0,0,1,0,1,0])


In [ ]:
np.random.seed(28)

ridedurations_length = np.random.choice([0, 1], size=(250,), p=[1./2, 1/2])
ridedurations_length

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1])

In [ ]:
ridedurations_lengths = repr(ridedurations_length).replace(" ", "")
print(ridedurations_lengths)

array([1,1,0,0,1,1,0,1,1,1,0,1,0,0,1,1,0,0,0,1,0,0,
1,1,1,1,0,0,1,0,1,1,0,0,1,0,1,1,1,0,0,1,0,1,
1,0,1,1,1,0,1,0,1,0,1,0,1,0,0,1,1,1,1,0,1,0,
1,0,1,0,1,0,1,1,0,0,0,1,0,1,0,1,0,1,1,0,1,1,
1,1,1,1,0,1,0,0,0,1,0,1,0,1,0,0,0,1,0,0,1,1,
1,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,1,1,0,1,0,1,
1,1,0,1,1,0,0,1,0,0,0,0,0,0,1,1,1,0,1,1,0,1,
1,1,0,0,0,1,0,0,1,1,0,0,1,0,0,0,0,1,1,1,0,1,
0,1,1,1,0,1,0,1,0,0,1,0,1,0,1,1,0,0,1,1,1,0,
0,0,1,1,0,1,1,0,0,0,1,0,0,1,0,0,1,1,0,0,1,1,
1,0,1,0,1,1,1,0,1,0,0,0,1,1,0,1,0,0,0,0,1,1,
1,1,0,0,0,0,0,1])


In [ ]:
waitingtime_short = repr(waitingtime_short).replace(".", "").replace(" ", "")
print(waitingtime_short)

array([3,3,4,4,4,3,2,5,3,3,4,4,2,3,5,5,3,
5,1,4,3,4,3,4,4,4,4,3,2,4,4,3,2,1,
4,5,5,3,2,5,2,5,4,3,4,3,4,5,2,4,4,
4,4,1,4,3,4,3,4,3])


In [ ]:
waitingtime_long = repr(waitingtime_long).replace(".", "").replace(" ", "")
print(waitingtime_long)

array([10,8,18,8,7,16,11,15,14,9,6,18,27,
15,11,14,9,11,9,10,11,12,9,19,10,14,
16,17,13,14,12,9,17,8,12,10,14,15,10,
9,12,14,7,10,24,11,13,15,11,10,12,11,
11,14,6,9,16,11,10,6,9,12,12,14,13,
18,8,21,16,15,17,10,10,12,10,7,9,11,
7,14,19,18,6,11,15,8,9,11,8,10,10,
10,10,12,7,8,15,10,12,15,5,19,5,15,
14,14,12,7,8,6,5,10,7,13,16,23,10,
17,10,14,8,11,6,17,19,12,8,7,9,9,
7,14,6,10,18,6,11,8,12,8,7,6,15,
9,11,11,10,6,11,23,8,11,14,11,14,10,
10,8,24,10,11,11,6,10,10,19,6,17,8,
5,13,11,12,13,9,13,14,15,9,9,13,11,
8,9,10,18,15,12,6,9,18,19,16,17,13,
13,5,5,13,14,17,12,16,7,13,8,18,12,
10,13,14,6,8,9,12,16,10,6,9,13,9,
8,9,14,8,6,20,15,21,15,13,9,14,8,
14,13,9,22,7,15,8,5,8,8,14,15,14,
7,8,15,15,9,11,13,5,8,12,10,13,15,
16,12,16,11,7,13,15,17,7,15,11,20,16,
11,13,9,12,20,12,6,13,12,10,7,18,8,
12,5,9,13,10,7,7,9,9,7,18,13,7,
10,10,14,12,6,8,9,12,17,9,8,16,14,
8,8,11,20,7,7,13,12,7,8,11,18,9,
11,15,10,16,11,19,9,8,11,8,15,11,6,
10,15,13,14,12,7,7,5,6,9,16,11,16,
9,13,10,12,9,11,16,12,13,9,12,15,9,


In [ ]:
rideduration_short
rideduration_short = repr(rideduration_short).replace(".", "").replace(" ", "")
print(rideduration_short)

array([13,25,14,27,23,17,16,29,20,28,28,32,30,
32,15,30,25,31,14,12,31,29,18,23,14,32,
21,30,31,22,30,26,13,2,31,33,25,29,24,
16,22,27,30,28,32,31,31,31,24,1,27,32,
17,11,13,19,18,19,23,27,18,21,19,25,32,
13,32,18,27,21,26,24,29,29,24,22,33,22,
26,26,9,25,23,31,33,17,14,15,20,12,28,
17,15,31,32,27,33,21,33,33,21,26,19,29,
28,29,15,17,27,30,33,22,30,14,19,19,24,
11,28,7,17,32,21,26,15,30,14,31,22,30,
28,26,30,27,22,10,28,28,31,23,28,19,26,
26,23,27,8,28,8,16,19,25,32,23,7,24,
18,18,12,10,30,22,32,18,23,27,20,29,32,
24,24,10,29,31,24,18,25,32,32,22,28,31,
29,27,27,16,26,25,23,25,27,13,30,32,16,
31,26,27,22,25,25,19,22,30,12,16,30,18,
29,30,28,9,15,32,5,17,29,30,33,15,15,
30,25,23,9,32,33,22,32,29,4,15,26,29,
30,29,20,30,22,12,16,27,22,31,25,20,13,
27,27,27,16,21,14,22])


In [ ]:
rideduration_long = repr(rideduration_long).replace(".", "").replace(" ", "")
print(rideduration_long)

array([33,52,48,35,45,43,55,78,47,35,44,36,36,
37,56,43,48,52,40,44,39,52,39,44,45,39,
43,33,70,35,41,45,34,37,35,34,44,48,34,
37,37,43,40,53,61,48,44,50,33,38,36,43,
55,54,34,45,34,38,45,36,45,58,45,44,43,
38,33,39,49,66,52,44,36,50,55,38,42,54,
34,38,45,34,34,36,68,34,44,34,43,70,35,
35,57,52,41,34,37,40,40,42,44,40,36,54,
45,37,55,57,48,50,40,41,41,43,51,39,47,
39,53,38,39,44,39,49,39,43,58,46,63,46,
41,42,43,39,65,45,42,45,43,46,44,34,40,
38,40,45,49,38,48,34,41,45,51,45,36,59,
47,35,42,37,58,37,42,37,53,37,41,55,39,
43,37,37,50,48,43,36,58,40,38,35,53,35,
46,49,34,55,35,46,36,33,45,41,42,38,47,
36,47,41,33,39,35,47,39,39,38,46,38,36,
48,44,40,42,43,52,39,36,36,45,46,39,43,
39,34,38,40,42,39,36,40,40,46,47,57,40,
38,33,35,47,55,38,43])


In [ ]:
arrays = [waitingtime_short, waitingtime_long,
          rideduration_short, rideduration_long]

for i in arrays:
  print(repr(i).replace(".", ","))

'array([3,3,4,4,4,3,2,5,3,3,4,4,2,3,5,5,3,\n5,1,4,3,4,3,4,4,4,4,3,2,4,4,3,2,1,\n4,5,5,3,2,5,2,5,4,3,4,3,4,5,2,4,4,\n4,4,1,4,3,4,3,4,3])'
'array([10,8,18,8,7,16,11,15,14,9,6,18,27,\n15,11,14,9,11,9,10,11,12,9,19,10,14,\n16,17,13,14,12,9,17,8,12,10,14,15,10,\n9,12,14,7,10,24,11,13,15,11,10,12,11,\n11,14,6,9,16,11,10,6,9,12,12,14,13,\n18,8,21,16,15,17,10,10,12,10,7,9,11,\n7,14,19,18,6,11,15,8,9,11,8,10,10,\n10,10,12,7,8,15,10,12,15,5,19,5,15,\n14,14,12,7,8,6,5,10,7,13,16,23,10,\n17,10,14,8,11,6,17,19,12,8,7,9,9,\n7,14,6,10,18,6,11,8,12,8,7,6,15,\n9,11,11,10,6,11,23,8,11,14,11,14,10,\n10,8,24,10,11,11,6,10,10,19,6,17,8,\n5,13,11,12,13,9,13,14,15,9,9,13,11,\n8,9,10,18,15,12,6,9,18,19,16,17,13,\n13,5,5,13,14,17,12,16,7,13,8,18,12,\n10,13,14,6,8,9,12,16,10,6,9,13,9,\n8,9,14,8,6,20,15,21,15,13,9,14,8,\n14,13,9,22,7,15,8,5,8,8,14,15,14,\n7,8,15,15,9,11,13,5,8,12,10,13,15,\n16,12,16,11,7,13,15,17,7,15,11,20,16,\n11,13,9,12,20,12,6,13,12,10,7,18,8,\n12,5,9,13,10,7,7,9,9,7,18,13,7,\n10,10,14,12,6,